### ISSUE TITLE
Typedef bug

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#3] opened 2012-10-18 21:21 UTC
Checked in to the regression suite (r124) as tests/rjs-basic/goofy-typedef1.c0 and tests/rjs-basic/goofy-typedef2.c0; the error is in cc0's parser/typechecker.

```
/* goofy-typedef1.c0 */
elem f(elem x) { return x; }
```

```
/* goofy-typedef2.c0 */
typedef int elem;
#use "goofy-typedef1.c0"
int main() { return f(16); }
```

```
$ cc0 goofy-typedef2.c0
Unexpected exception in cc0:
nonexhaustive match failure
```

**Comment by frankpfenning** [comment] 2012-12-22 15:34
Fixing this bug would require a major restructuring of the implementation.

Turns out, it doesn't directly have to do with typedefs, although
this was a reasonable use case where it showed up.

The problem is the following phase distinction:
1. Parse a file into a list of global declarations.
   In this phase, we do not populate Symtab, only Typetab
   because parsing is affected by what is known to be a defined
   type name.
2. Type-check each of the global declarations in sequence.
   Let's call this elaboration.  In this phase, we populate Symtab with "clean",
   that is, type-checked definitions.

When we hit #use "file.c0" we follow the exact steps 1 and 2
for this file.  And then proceed recursively.

The bug appears in a situation

... some global definitions ...
#use "usefile.c0"

The global definitions preceding "usefile.c0" have not yet been
elaborated, when we start the elaboration phase 2 for "usefile.c0". 
This violates the fundamental invariant that global declarations are elaborated in
sequence.

We could try to elaborate each global declaration as we encounter it.
Because elaboration includes transformation for the purpose of
implementation, checking of contracts (with -d) this is a bit complicated,
but I think it is possible.  It is complicated further by the stipulation that we process
only the temporally first occurrence of #use for any library or file.

Alternatively, we could specify that #use declarations cannot be preceded
by ordinary declarations.  If we wanted to use type parameters for common
data structures, we would either have to define them in a file that we
#use, or we would have to make them structs (making the interaction
between libraries written in C0 and C0 clients more symmetric).

The second would be quite easy to implement, since we only have
to check when processing libraries that they are not preceded by
(unelaborated) declarations.  I am not quite sure about all the consequences
of the first.

Thoughts?

**Comment by robsimmons** [comment] 2012-12-22 15:45
Seems like the reason we didn't notice the bug for a long time is that
standard usage doesn't have us preceding #use with global declarations.

The second solution, limiting the language, seems like a reasonable
medium-to-long term fix if the "good" fix breaks the language. It's
consistent with good C style.

**Comment by robsimmons** [comment] 2012-12-22 15:47
Should have said: if the "good" fix complicates the implementation (not
"breaks the language")

**Comment by frankpfenning** [comment] 2012-12-22 23:42
Fixed, by forcing all #use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Comment by frankpfenning** [comment] 2012-12-22 23:42
Fixed, by forcing all #use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Comment by frankpfenning** [comment] 2012-12-22 23:43
Fixed, by forcing all #use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Comment by frankpfenning** [comment] 2012-12-22 23:43
Fixed, by forcing all #use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Comment by frankpfenning** [comment] 2012-12-22 23:43
Fixed, by forcing all use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Closed as completed by frankpfenning** 2012-12-22 23:42 UTC
Labels: cc0, bug-inregression

**Comment by frankpfenning** [comment] 2012-12-22 23:44
Fixed, by forcing all use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Comment by frankpfenning** [comment] 2012-12-22 23:44
Fixed, by forcing all use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Comment by frankpfenning** [comment] 2012-12-22 23:45
Fixed, by forcing all use directives to precede all other declarations.

This condition is now checked in parse3.sml.  Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194

**Comment by frankpfenning** [comment] 2012-12-22 23:49
Fixed, by forcing all use directives to precede all other declarations.

This condition is now checked in parse3.sml. Also updated the parser
to track regions for pragmas to provide better error messages.

Changes available as of r194
